name: CI

on:
  push:
    branches: [ build ]

jobs:
  build_windows:
    timeout-minutes: 30
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - uses: jwlawson/actions-setup-cmake@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build ${{matrix.parallel_backend}}
      shell: powershell
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DMANIFOLD_DEBUG=ON -DMANIFOLD_CBIND=ON -DMANIFOLD_PAR=ON -A x64 -B build
        cd build
        cmake --build . --target ALL_BUILD --config Release
    - name: Test ${{matrix.parallel_backend}}
      shell: bash
      run: |
        cd build/bin/Release
        ./manifold_test.exe
        cd ../../
    - name: test cmake consumer
      run: |
        cd build
        cmake --install .
        cd ..
        ./scripts/test-cmake.sh
